added new json functions
project-flogo/contrib pull request #140
Opened 2021-06-24 12:11 UTC by awakchau-tibco

Added new json functions like get, length, numbersToString, objKeys, objValues and set.

2021-07-07 02:28 UTC, lixingwang requested changes

2021-07-07 02:28 UTC, lixingwang commented on function/json/descriptor.json
> +      "description": "Get the number of elements in a json object",
length should also compatible to array

2021-07-07 02:28 UTC, lixingwang commented on function/url/encode.go
> +		baseURL.Fragment += u.Fragment
we should also escape fragment, such as path also need to be escaped

2021-07-07 11:51 UTC, awakchau-tibco commented on function/json/descriptor.json
> +      "description": "Get the number of elements in a json object",
updated the json function description to support array

2021-07-07 12:01 UTC, awakchau-tibco commented on function/url/encode.go
> +		baseURL.Fragment += u.Fragment
@lixingwang we already escape path, query and fragment part of the URL. I've updated the test case to include all 3 parameters. For example:
`Input : https://subdomain.example.com/path to be escaped?q=hello world#fragment with space`
`Output: https://subdomain.example.com/path%20to%20be%20escaped?q=hello+world#fragment%20with%20space`

2021-07-08 13:59 UTC, lixingwang approved these changes

2021-07-08 13:59 UTC, merged